name: Validate Master

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure Build
        uses: vgaidarji/android-github-actions/build@v1.0.0

      - name: Unit Tests
        run: ./gradlew test

      - name: Android Tests
        uses: vgaidarji/android-github-actions-emulator@v1.0.1

      - name: Build Project
        run: ./gradlew assemble
